url-base := https://toolchains.bootlin.com/downloads/releases/toolchains

# arch libc tag version
mk-url = $(url-base)/$(1)/tarballs/$(1)--$(2)--$(3)-$(4)

archs := \
  aarch64 \
  aarch64be \
  arcle-750d \
  arcle-hs38 \
  armebv7-eabihf \
  armv5-eabi \
  armv6-eabihf \
  armv7-eabihf \
  armv7m \
  bfin \
  m68k-68xxx \
  m68k-coldfire \
  microblazebe \
  microblazeel \
  mips32 \
  mips32el \
  mips32r5el \
  mips32r6el \
  mips64-n32 \
  mips64el-n32 \
  mips64r6el-n32 \
  nios2 \
  openrisc \
  powerpc-440fp \
  powerpc-e300c3 \
  powerpc-e500mc \
  powerpc64-e5500 \
  powerpc64-e6500 \
  powerpc64-power8 \
  powerpc64le-power8 \
  riscv32-ilp32d \
  riscv64-lp64d \
  s390x-z13 \
  sh-sh4 \
  sh-sh4aeb \
  sparc64 \
  sparcv8 \
  x86-64 \
  x86-64-core-i7 \
  x86-64-v2 \
  x86-64-v3 \
  x86-64-v4 \
  x86-core2 \
  x86-i686 \
  xtensa-lx60

libcs := \

